%global __python %{__python3}

Name:       sdk-harbour-rpmvalidator
Summary:    Jolla Harbour RPM validation tools
Version:    1.2
Release:    1
License:    GPLv2
BuildArch:  noarch
URL:        https://github.com/sailfishos/sdk-harbour-rpmvalidator
BuildRequires: python3-base
Provides:   default-rpm-validation-suite
Requires:   binutils
Requires:   coreutils
Requires:   findutils
Requires:   sed
Requires:   cpio
Requires:   file
Requires:   grep
Source0:    %{name}-%{version}.tar.bz2
Source100:  update-tests-requires.sh

%description
RPM validation tools for Jolla Harbour.

%define debug_package %{nil}

%package sdk-tests
Summary: Verifies that the SDK really provides what %{name} promises
Requires: %{name} = %{version}-%{release}
Requires: python3-base

# --auto-test-requires-BEGIN--
# Autogenerated by ./update-tests-requires.sh - do not edit manually
Requires: qml(Nemo.Configuration)
Requires: qml(Nemo.DBus)
Requires: qml(Nemo.Notifications)
Requires: qml(Nemo.Thumbnailer)
Requires: qml(QtGraphicalEffects)
Requires: qml(QtMultimedia)
Requires: qml(QtPositioning)
Requires: qml(QtQml)
Requires: qml(QtQml.Models)
Requires: qml(QtQuick)
Requires: qml(QtQuick.Layouts)
Requires: qml(QtQuick.LocalStorage)
Requires: qml(QtQuick.Particles)
Requires: qml(QtQuick.Window)
Requires: qml(QtQuick.XmlListModel)
Requires: qml(QtSensors)
Requires: qml(QtWebKit)
Requires: qml(Sailfish.Pickers)
Requires: qml(Sailfish.Silica)
Requires: qml(io.thp.pyotherside)
Requires: qml(org.freedesktop.contextkit)
# --auto-test-requires-END--

%description sdk-tests
%{summary}.

%package doc
Summary: Documentation for Harbour RPM Validator
BuildRequires: python3dist(mako)

%description doc
%{summary}.

%prep
%setup -q

%build
./sdk-tests/check-qml-typeinfo.py -a allowed_qmlimports.conf \
                                  create-tests-xml > sdk-tests/tests.xml
./doc/gen_doc.py -t html > doc/harbour_allowed_apis.html
./doc/gen_doc.py -t md > doc/harbour_allowed_apis.md
./doc/gen_doc.py -t md -l permissions > doc/harbour_allowed_permissions.md

%install
rm -rf %{buildroot}

install -D -m 0755 rpmvalidation.sh %{buildroot}%{_libexecdir}/%{name}/rpmvalidation.sh
install -D -m 0644 allowed_libraries.conf %{buildroot}%{_datadir}/%{name}/allowed_libraries.conf
install -D -m 0644 allowed_qmlimports.conf %{buildroot}%{_datadir}/%{name}/allowed_qmlimports.conf
install -D -m 0644 allowed_requires.conf %{buildroot}%{_datadir}/%{name}/allowed_requires.conf
install -D -m 0644 deprecated_libraries.conf %{buildroot}%{_datadir}/%{name}/deprecated_libraries.conf
install -D -m 0644 deprecated_qmlimports.conf %{buildroot}%{_datadir}/%{name}/deprecated_qmlimports.conf
install -D -m 0644 deprecated_requires.conf %{buildroot}%{_datadir}/%{name}/deprecated_requires.conf
install -D -m 0644 disallowed_qmlimport_patterns.conf %{buildroot}%{_datadir}/%{name}/disallowed_qmlimport_patterns.conf
install -D -m 0644 allowed_sailjailkeys.conf %{buildroot}%{_datadir}/%{name}/allowed_sailjailkeys.conf
install -D -m 0644 allowed_permissions.conf %{buildroot}%{_datadir}/%{name}/allowed_permissions.conf
install -D -m 0644 disallowed_orgnames.conf %{buildroot}%{_datadir}/%{name}/disallowed_orgnames.conf
install -D -m 0644 rpmvalidation.conf %{buildroot}%{_datadir}/%{name}/rpmvalidation.conf
install -D -m 0644 harbour.ini %{buildroot}%{_datadir}/rpmvalidation/suites/harbour.ini

# create version information file that is read by the validation script
echo "%{version}-%{release}" > %{buildroot}%{_datadir}/%{name}/version

install -D -m 0755 sdk-tests/check-qml-typeinfo.py %{buildroot}/opt/tests/%{name}/check-qml-typeinfo.py
install -D -m 0644 sdk-tests/tests.xml %{buildroot}/opt/tests/%{name}/tests.xml

install -D -m 0644 doc/harbour_allowed_apis.html %{buildroot}/%{_docdir}/%{name}/harbour_allowed_apis.html
install -D -m 0644 doc/harbour_allowed_apis.md %{buildroot}/%{_docdir}/%{name}/harbour_allowed_apis.md
install -D -m 0644 doc/harbour_allowed_permissions.md %{buildroot}/%{_docdir}/%{name}/harbour_allowed_permissions.md

%files
%defattr(-,root,root,-)
%{_libexecdir}/%{name}/rpmvalidation.sh
%{_datadir}/%{name}/version
%{_datadir}/%{name}/*.conf
%{_datadir}/rpmvalidation/suites/harbour.ini

%files sdk-tests
%defattr(-,root,root,-)
/opt/tests/%{name}/*

%files doc
%defattr(-,root,root,-)
%dir %{_docdir}/%{name}
%{_docdir}/%{name}/*
